param grafana_grfvkgyyrfx_name string

resource grafana_grfvkgyyrfx_name_resource 'Microsoft.Dashboard/grafana@2025-09-01-preview' = {
  name: grafana_grfvkgyyrfx_name
  location: 'norwayeast'
  sku: {
    name: 'Standard'
    size: 'X1'
  }
  properties: {
    zoneRedundancy: 'Disabled'
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    apiKey: 'Disabled'
    creatorCanAdmin: 'Disabled'
    deterministicOutboundIP: 'Disabled'
    grafanaIntegrations: {
      azureMonitorWorkspaceIntegrations: []
    }
    grafanaConfigurations: {
      smtp: {
        enabled: false
      }
    }
    grafanaMajorVersion: '12'
  }
}

