@secure()
param webhooks_wh8jol6k_serviceUri string
param registries_acrhuv0ipc0_name string

resource registries_acrhuv0ipc0_name_resource 'Microsoft.ContainerRegistry/registries@2026-01-01-preview' = {
  name: registries_acrhuv0ipc0_name
  location: 'norwayeast'
  sku: {
    name: 'Standard'
    tier: 'Standard'
  }
  properties: {
    adminUserEnabled: false
    policies: {
      quarantinePolicy: {
        status: 'disabled'
      }
      trustPolicy: {
        type: 'Notary'
        status: 'disabled'
      }
      retentionPolicy: {
        days: 7
        status: 'disabled'
      }
      exportPolicy: {
        status: 'enabled'
      }
      azureADAuthenticationAsArmPolicy: {
        status: 'enabled'
      }
      softDeletePolicy: {
        retentionDays: 7
        status: 'disabled'
      }
    }
    encryption: {
      status: 'disabled'
    }
    dataEndpointEnabled: false
    regionalEndpoints: 'Disabled'
    endpointProtocol: 'IPv4'
    publicNetworkAccess: 'Enabled'
    networkRuleBypassOptions: 'AzureServices'
    networkRuleBypassAllowedForTasks: false
    zoneRedundancy: 'Disabled'
    anonymousPullEnabled: false
    metadataSearch: 'Disabled'
    roleAssignmentMode: 'LegacyRegistryPermissions'
    autoGeneratedDomainNameLabelScope: 'Unsecure'
  }
}

resource registries_acrhuv0ipc0_name_repositories_admin 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registries_acrhuv0ipc0_name_resource
  name: '_repositories_admin'
  properties: {
    description: 'Can perform all read, write and delete operations on the registry'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
      'repositories/*/content/delete'
    ]
  }
}

resource registries_acrhuv0ipc0_name_repositories_pull 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registries_acrhuv0ipc0_name_resource
  name: '_repositories_pull'
  properties: {
    description: 'Can pull any repository of the registry'
    actions: [
      'repositories/*/content/read'
    ]
  }
}

resource registries_acrhuv0ipc0_name_repositories_pull_metadata_read 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registries_acrhuv0ipc0_name_resource
  name: '_repositories_pull_metadata_read'
  properties: {
    description: 'Can perform all read operations on the registry'
    actions: [
      'repositories/*/content/read'
      'repositories/*/metadata/read'
    ]
  }
}

resource registries_acrhuv0ipc0_name_repositories_push 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registries_acrhuv0ipc0_name_resource
  name: '_repositories_push'
  properties: {
    description: 'Can push to any repository of the registry'
    actions: [
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

resource registries_acrhuv0ipc0_name_repositories_push_metadata_write 'Microsoft.ContainerRegistry/registries/scopeMaps@2026-01-01-preview' = {
  parent: registries_acrhuv0ipc0_name_resource
  name: '_repositories_push_metadata_write'
  properties: {
    description: 'Can perform all read and write operations on the registry'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

resource registries_acrhuv0ipc0_name_wh8jol6k 'Microsoft.ContainerRegistry/registries/webhooks@2026-01-01-preview' = {
  parent: registries_acrhuv0ipc0_name_resource
  name: 'wh8jol6k'
  location: 'norwayeast'
  properties: {
    status: 'disabled'
    actions: [
      'push'
    ]
    serviceUri: webhooks_wh8jol6k_serviceUri
  }
}

