using System.Text;
using System.Text.Json;

namespace AzResourceDetailsDownloader.Templating;

// Turns a real capture's portal-fields.json (the layout — which fields, in the order Azure's own
// UI chose to show them) plus FieldRecipeResolver's per-field resolution into a Scriban template
// body: an Essentials-style markdown table any resource of that armType can be rendered against,
// not just the one captured here.
//
// Per the three-way split settled on for how to handle a field the resolver couldn't cleanly
// resolve: the row is always kept (dropping it would silently break layout parity with the
// portal), filled with a TODO comment plus the captured example's value as a hint rather than
// either omitting the row or baking in that one example as if it were universally true.
public static class TemplateGenerator
{
    // Matches AzToMd's own TypeToKey exactly (dots/slashes -> underscores, lowercased) — not
    // because ARDL depends on AzToMd, but so a generated file is drop-in-named if it's ever handed
    // to a renderer that resolves templates by that convention.
    public static string TypeToKey(string armType) =>
        armType.Replace('.', '_').Replace('/', '_').ToLowerInvariant();

    public static string Generate(string armType, IReadOnlyList<(string Label, string Value)> fields, JsonElement root)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"{{{{~ # Auto-generated by AzResourceDetailsDownloader --generate-templates for {armType}. ~}}}}");
        sb.AppendLine("{{~ # Requires these custom Scriban functions registered on the rendering engine: ~}}");
        sb.AppendLine("{{~ # portal_bool_enabled, portal_bool_yesno, portal_timestamp, region_display_name — see TemplateFunctions.cs. ~}}");
        sb.AppendLine("{{~ # Rows marked TODO could not be mechanically resolved against the captured example — see config/portal-field-recipes.json for why. ~}}");
        sb.AppendLine($"# {{{{ model.name }}}}");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("|---|---|");

        foreach (var (label, value) in fields)
        {
            var recipe = FieldRecipeResolver.Resolve(label, value, root, armType);
            var row = BuildRow(label, value, recipe, root);
            if (row is not null)
            {
                sb.AppendLine(row);
            }
        }

        return sb.ToString();
    }

    private static string? BuildRow(string label, string value, FieldRecipe recipe, JsonElement root)
    {
        var escapedLabel = EscapeForTable(label);

        if (recipe.Kind == FieldRecipeKind.Context)
        {
            // Tenant/subscription identity — already covered by the vault's frontmatter (see
            // FieldRecipeResolver's Context notes); omitting the row here doesn't break layout
            // parity the way dropping a genuinely-portal-visible field would; the comment
            // documents *why* it's missing rather than leaving a silent gap.
            return $"<!-- \"{escapedLabel}\" omitted: tenant/subscription identity, already in frontmatter -->";
        }

        var expression = ExpressionFor(recipe, value, root);

        if (expression is null)
        {
            if (recipe.IsLiveState)
            {
                // No captured value is trustworthy here at all — unlike a resolved live-state field
                // (handled below, still shows a real value with a staleness caveat), there's nothing
                // to show but a stale example that was never guaranteed to reflect any *other*
                // resource of this type in the first place. Showing it as a "TODO: investigate" like
                // every other unresolved field would suggest a mapping is waited on; for a genuinely
                // live condition (a VM's power state isn't even in ARDL's capture body), there may
                // never be a static answer, so say so plainly instead.
                return $"| **{escapedLabel}** | *See the Azure Portal for current status.* |";
            }

            // Unresolved / NeedsReview / Ambiguous / NotAddressable / ShortcutMismatch / etc. — keep
            // the row so the table's shape still matches the portal's, but don't pretend to have a
            // real source: show a TODO plus the one example value actually captured, as a hint for
            // whoever finishes this by hand.
            var hint = EscapeForTable(recipe.Notes);
            var exampleValue = EscapeForTable(value);
            return $"| **{escapedLabel}** | <!-- TODO ({recipe.Kind}): {hint} --> {exampleValue} |";
        }

        if (recipe.IsLiveState)
        {
            // A value that's true right now, not durably — keep the row (see class comment) but
            // mark it as a snapshot rather than a live fact.
            expression = $"{expression} <sub>(as of last sync)</sub>";
        }

        return $"| **{escapedLabel}** | {expression} |";
    }

    // Returns the Scriban expression (without the surrounding "{{ }}") for a resolvable recipe, or
    // null when there's nothing safe to reference — the caller falls back to a TODO row either way.
    private static string? ExpressionFor(FieldRecipe recipe, string value, JsonElement root)
    {
        switch (recipe.Kind)
        {
            // model.location always needs the region_display_name transform regardless of which
            // shortcut tier resolved it — Verified/Shortcut/CasingMismatch all mean "the raw ARM
            // value differs from the portal's display text", just with different confidence about
            // whether config/azure-locations.json's answer is right. The transform is safe to apply
            // unconditionally: it falls back to the raw code unchanged for anything not in the
            // table (e.g. "global"), so applying it to an already-display-form value is a no-op.
            case FieldRecipeKind.ShortcutVerified or FieldRecipeKind.Shortcut or FieldRecipeKind.ShortcutCasingMismatch
                when recipe.Target == "model.location":
                return $"{{{{ {recipe.Target} | region_display_name }}}}";

            case FieldRecipeKind.ShortcutVerified:
                return $"{{{{ {recipe.Target} }}}}";

            case FieldRecipeKind.Shortcut:
                // Not verified against this specific capture (e.g. a region missing from
                // config/azure-locations.json) — still usable, the raw value just might not match
                // the portal's exact text for every instance of this type.
                return $"{{{{ {recipe.Target} }}}}";

            case FieldRecipeKind.ShortcutCasingMismatch:
                return $"{{{{ {recipe.Target} | string.capitalize }}}}";

            case FieldRecipeKind.Timestamp:
                return $"{{{{ {recipe.Target} | portal_timestamp }}}}";

            case FieldRecipeKind.Boolean:
            {
                var transform = ChooseBoolTransform(value);
                return IsRealJsonBoolean(root, recipe.Target)
                    ? $"{{{{ {recipe.Target} | {transform} }}}}"
                    : $"{{{{ {recipe.Target} }}}}"; // already a display-ready string (e.g. "Enabled"), no transform needed
            }

            case FieldRecipeKind.Direct:
            {
                // The generic resolver also matches plain booleans under "Direct" (see
                // FieldRecipeResolver.TryMatchLeafValue's "boolean→friendly-word" reason) — same
                // transform decision as the Boolean case above, just reached through a different path.
                if (recipe.Notes.Contains("boolean", StringComparison.OrdinalIgnoreCase)
                    && IsRealJsonBoolean(root, recipe.Target))
                {
                    return $"{{{{ {recipe.Target} | {ChooseBoolTransform(value)} }}}}";
                }

                // Matching is case-insensitive (see FieldRecipeResolver's Normalize-based
                // comparison), so a "Direct" match can still differ from the portal's exact text by
                // casing alone — live-observed: Container Registry's raw policy status is
                // "disabled", the portal shows "Disabled". Only worth fixing the common single-word
                // enum case; a genuinely different value would never have Normalize-matched at all.
                var rawText = TryGetRawLeafText(root, recipe.Target);
                if (rawText is not null && rawText != value && !rawText.Contains(' '))
                {
                    return $"{{{{ {recipe.Target} | string.capitalize }}}}";
                }
                return $"{{{{ {recipe.Target} }}}}";
            }

            default:
                // NeedsReview, Ambiguous, Unresolved, NotAddressable, ShortcutMismatch,
                // TimestampUnresolved — a Target may exist (e.g. NeedsReview) but isn't trusted
                // enough to reference unattended; falls through to the TODO row.
                return null;
        }
    }

    private static string ChooseBoolTransform(string capturedValue) =>
        PortalFieldKnowledge.Normalize(capturedValue) is "yes" or "no" ? "portal_bool_yesno" : "portal_bool_enabled";

    // Only apply a portal_bool_* transform to an actual JSON true/false — a raw property that's
    // already a display-ready string ("Enabled"/"Disabled" as literal ARM enum text, e.g.
    // publicNetworkAccess) needs no transform, and piping a string through a function expecting a
    // bool would just misrender. Best-effort: any path Navigate can't follow (e.g. an array index
    // segment) falls back to "not a boolean", which just skips the transform rather than crashing.
    private static bool IsRealJsonBoolean(JsonElement root, string? target) =>
        TryNavigateTarget(root, target) is { ValueKind: JsonValueKind.True or JsonValueKind.False };

    private static string? TryGetRawLeafText(JsonElement root, string? target) =>
        TryNavigateTarget(root, target) is { ValueKind: JsonValueKind.String } leaf ? leaf.GetString() : null;

    private static JsonElement? TryNavigateTarget(JsonElement root, string? target)
    {
        if (target is not { Length: > 0 } || !target.StartsWith("model.props.", StringComparison.Ordinal))
        {
            return null;
        }
        var segments = new List<string> { "properties" };
        segments.AddRange(target["model.props.".Length..].Split('.'));
        if (segments.Any(s => s.Contains('[')))
        {
            return null;
        }
        return JsonTree.Navigate(root, segments.ToArray());
    }

    private static string EscapeForTable(string s) => s.Replace("|", "\\|").Replace("\n", " ").Replace("\r", "");
}
